server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name samartin.42.fr;

    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;

    root  /var/www/localhost/htdocs;
    index index.php index.html;

    # WordPress: allow permalinks by routing missing files to index.php
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Deny access to hidden files (.htaccess, .git, etc.)
    location ~ /\.(?!well-known) {
        deny all;
    }

    # PHP handling
    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_index index.php;

        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}