services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database:/var/lib/mysql
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/localhost/htdocs
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./web:/var/lib/nginx/html
