services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./web:/var/www/html
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#      - ./web:/var/www/html
